# our base image
FROM alpine

# Install python and pip
RUN apk add --update py3-pip

# upgrade pip
RUN pip install --upgrade pip

# install Python modules needed by the Python app
RUN pip3 install paho-mqtt

# copy files required for the app to run
COPY sisub.py /usr/src/app/

# tell the port number the container should expose
EXPOSE 5000

# run the application
CMD ["python3", "/usr/src/app/sisub.py"]